name: Checks

on:
  push:
    branches:
      "master"

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9.18"
    - name: Install Poetry
      uses: abatilo/actions-poetry@v4
      with:
        poetry-version: "2.1.3"
    - uses: actions/cache@v4
      name: Define a dependencies cache
      with:
        path: ./.venv
        key: venv-${{ hashFiles('poetry.lock') }}
    - name: Install dependencies
      run: poetry install --with dev
    - name: Run checks
      run: make check